# Generated by Django 3.2.4 on 2021-06-23 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcode',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 23, 9, 27, 34, 252909, tzinfo=utc)),
        ),
    ]
