# Generated by Django 3.2.4 on 2021-06-25 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210623_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='register_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2001, 1, 1)),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Name', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='Surname', max_length=23),
        ),
    ]
