# Generated by Django 3.2.4 on 2021-06-28 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='./logo/default.png', upload_to='./Profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 12, 18, 29, 487506, tzinfo=utc)),
        ),
    ]
