# Generated by Django 3.2.4 on 2021-07-02 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210630_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_time',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 11, 22, 24, 334235, tzinfo=utc)),
        ),
    ]
