# Generated by Django 3.2.4 on 2021-07-06 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210706_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 10, 35, 50, 74200, tzinfo=utc)),
        ),
    ]
