# Generated by Django 3.2.4 on 2021-07-06 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_message_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 11, 56, 52, 117443, tzinfo=utc)),
        ),
    ]
