# Generated by Django 3.2.4 on 2021-07-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210706_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_date',
            field=models.DateTimeField(default='07/07/2021, 08:22:28'),
        ),
    ]
